build:
	@echo building api...
	@cargo build --manifest-path src/components/api/Cargo.toml
	@echo finished...
	@echo building db...
	@cargo build --manifest-path src/components/db/Cargo.toml
	@echo finished...
	@echo building service...
	@cargo build --manifest-path src/components/service/Cargo.toml
	@echo finished...

run:
	@echo starting api...
	@cargo run --manifest-path src/components/api/Cargo.toml
	@echo api started...
	@echo starting db...
	@cargo run --manifest-path src/components/db/Cargo.toml
	@echo db started...
	@echo starting service...
	@cargo run --manifest-path src/components/service/Cargo.toml
	@echo service started...
